export const CONSULTANT_AVAILABILITY_BEGINNING_HOUR = 19; // in hrs 24-hr time
export const CONSULTANT_AVAILABILITY_ENDING_HOUR = 21;
export const CONSULTANT_AVAILABILITY_INTERVAL = 15; // in minutes

