name: Building and Running Applicat 

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted 

    steps:
      - name: Checking out the files
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: bun i

      - name: copying env files
        run: |
          cp /home/applicat/.applicat-env ./env

      - name: Building :)
        run: bun run build

      - name: Running the application using pm2
        run: |
          prevProcesses=$(pm2 ls | grep -i "applicat")

          if [ -z "$prevProcesses"  ]; then
             # pm2 start "bun start" --name applicat
             echo "should start $prevProcesses"
          else
             # pm2 restart applicat 
             echo "should restart"
          fi

          pm2 save --force
